/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viajes;

import com.mysql.jdbc.Connection;
import conexion.conexion;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Bmarc
 */
public class InterfacePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfacePrincipal
     */
    public InterfacePrincipal() {
        initComponents();
        jdeskprincipal.setBorder(new imagenfondo());
        this.setExtendedState(MAXIMIZED_BOTH);
    }
public boolean VentanaCerrada(Object obj) {
        JInternalFrame[] activos = jdeskprincipal.getAllFrames();
        boolean cerrado = true;
        int i = 0;
        while (i < activos.length && cerrado) {
            if (activos[i] == obj) {
                cerrado = false;
            }
            i++;
        }
        return cerrado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdeskprincipal = new javax.swing.JDesktopPane();
        jmenuInterfaces = new javax.swing.JMenuBar();
        jmenuitemVehiculos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmenuReportes = new javax.swing.JMenu();
        jMenuReporteAutos = new javax.swing.JMenuItem();
        jmenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdeskprincipalLayout = new javax.swing.GroupLayout(jdeskprincipal);
        jdeskprincipal.setLayout(jdeskprincipalLayout);
        jdeskprincipalLayout.setHorizontalGroup(
            jdeskprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1697, Short.MAX_VALUE)
        );
        jdeskprincipalLayout.setVerticalGroup(
            jdeskprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );

        jmenuitemVehiculos.setText("Interfaces");
        jmenuitemVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuitemVehiculosActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Vehiculos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmenuitemVehiculos.add(jMenuItem1);

        jmenuInterfaces.add(jmenuitemVehiculos);

        jmenuReportes.setText("Reportes");

        jMenuReporteAutos.setText("Autos");
        jMenuReporteAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReporteAutosActionPerformed(evt);
            }
        });
        jmenuReportes.add(jMenuReporteAutos);

        jmenuInterfaces.add(jmenuReportes);

        jmenuSalir.setText("Salir");
        jmenuInterfaces.add(jmenuSalir);

        setJMenuBar(jmenuInterfaces);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdeskprincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdeskprincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
InterfaceAuto au;
    private void jmenuitemVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuitemVehiculosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmenuitemVehiculosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (VentanaCerrada(au)) {
            au = new InterfaceAuto();
            jdeskprincipal.add(au);
            au.setVisible(true);
            au.setResizable(false);
            //Centrar la ventana Autos
            Dimension desktopSize = jdeskprincipal.getSize();
            Dimension FrameSize = au.getSize();
            au.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            au.show();
            //
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya esta abierta");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuReporteAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReporteAutosActionPerformed
        try {
            // TODO add your handling code here:
            //conectarme
            conexion cc = new conexion();
            Connection cn = cc.conectar();
            JasperReport  reporte = JasperCompileManager.compileReport("C:\\Users\\Bmarc\\Documents\\NetBeansProjects\\Viajes\\src\\Reportes\\reporteAutos.jrxml");
            //JasperReport  reporte = JasperCompileManager.compileReport("C:\\Users\\Bmarc\\Documents\\NetBeansProjects\\Viajes\\src\\Reportes\\reportgrafico.jrxml");
            
            JasperPrint print = JasperFillManager.fillReport(reporte,null,cn);
            JasperViewer.viewReport(print);
        } catch (JRException ex) {
            Logger.getLogger(InterfacePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuReporteAutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuReporteAutos;
    public static javax.swing.JDesktopPane jdeskprincipal;
    private javax.swing.JMenuBar jmenuInterfaces;
    public static javax.swing.JMenu jmenuReportes;
    private javax.swing.JMenu jmenuSalir;
    private javax.swing.JMenu jmenuitemVehiculos;
    // End of variables declaration//GEN-END:variables
}
